Adding resource loading, along with caching and batching mechanisms
Pitchstone-Development-Group/Pitchstone-Editor pull request #3
Opened 2022-12-12 03:56 UTC by Ari-Atori

Every change in include/windows/libavformat/ and bin/ are just to load the missing ffmpeg libraries
All relevant code changes are in src/ folder

2022-12-13 15:38 UTC, RickyAndreFlores requested changes
Good job overall in getting the core functionality, most comments were about style and using similar functionality but with C++ alternatives that have some advantages.

2022-12-13 15:38 UTC, RickyAndreFlores commented on src/media/Media.cpp
>              goto done;
We should avoid using goto, its consider bad practice and generally avoided because it makes it harder to debug when flow control jumps around. We can use things like break, to get out of this loop and get similar results

2022-12-13 16:57 UTC, Ari-Atori commented on src/media/Media.hpp
>      void clean(MediaCache*);
Gonna run the same tests again using shared pointers tonight, since even though the contents of the media packet don't have to be thread safe, the reference count does, and is satisfactory
That should actually clean a lot of code up since I am manually doing the references
Although I will still need mutexes in Media since the list of shared pointers itself is not thread safe

2022-12-13 17:10 UTC, Ari-Atori commented on src/media/Media.cpp
>      mutex.lock();
Media is a class that represents a specific media file in the project, and it mainly houses already processed frames and other useful data. The Resource class is what actually reads into the media file. The Resource class first hooks up the file name it has to the MediaBin ( a list of media files), and gets a pointer to the Media instance representing the file it is trying to open.

The use for this is the store cache of already processed frames, and, if another track or thread has read the same frames, the Resource class can utilize those instead of processing the frames on its own. This reduces redundant memory and because of how interframe compression works in video formats, also stores future frames.

2022-12-13 17:22 UTC, Ari-Atori commented on src/media/Media.cpp
>              goto done;
Normally, I would say goto can be appropriate only if

1) You are getting out of a nested loop, as this reduces the number of control points at each layer, or
2) You are dealing with multiple points of failure where all result in freeing the same set of memory

And you are only going forward with them, and never allow looping back afterwards

But I don't see any of those cases above, good catch

2022-12-21 05:44 UTC, Ari-Atori commented on src/media/Media.hpp
>  #define MC_META_SIZE 8
Solved by making it static const var in class

2022-12-21 05:44 UTC, Ari-Atori commented on src/media/Media.hpp
>      Media(uint32_t indices);
Fixed

2022-12-21 05:44 UTC, Ari-Atori commented on src/media/Media.hpp
> +#define MC_IS_AV(mc) ((mc->format >= MC_AV_VISUAL) && (mc->format <= MC_AV_OTHER))
Fixed by making it function in MediaCache class

2022-12-21 05:45 UTC, Ari-Atori commented on src/media/Media.hpp
>      void clean(MediaCache*);
Transitioned them to shared pointers

2022-12-21 05:48 UTC, Ari-Atori commented on src/sys/domain.hpp
>  class domain {
I normally leave purely mathematical structures as lower case, as I do here.
This structure represents a union of sets of reals which can describe a domain.

2022-12-21 05:49 UTC, Ari-Atori commented on src/media/Media.cpp
>              goto done;
Actually, changed my mind. Replaced it all with try and catch system.

2022-12-21 05:50 UTC, Ari-Atori commented on src/media/Resource.hpp
> +#define RESOURCE_PLAY_FORWARD 0
Fixed

2022-12-26 23:07 UTC, merged